// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: favorite.proto

package message

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DouyinFavoriteActionRequest struct {
	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token      string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	VideoId    int64  `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ActionType int32  `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
}

func (m *DouyinFavoriteActionRequest) Reset()         { *m = DouyinFavoriteActionRequest{} }
func (m *DouyinFavoriteActionRequest) String() string { return proto.CompactTextString(m) }
func (*DouyinFavoriteActionRequest) ProtoMessage()    {}
func (*DouyinFavoriteActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d331d96d24e0e82b, []int{0}
}
func (m *DouyinFavoriteActionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DouyinFavoriteActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DouyinFavoriteActionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DouyinFavoriteActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DouyinFavoriteActionRequest.Merge(m, src)
}
func (m *DouyinFavoriteActionRequest) XXX_Size() int {
	return m.Size()
}
func (m *DouyinFavoriteActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DouyinFavoriteActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DouyinFavoriteActionRequest proto.InternalMessageInfo

func (m *DouyinFavoriteActionRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DouyinFavoriteActionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DouyinFavoriteActionRequest) GetVideoId() int64 {
	if m != nil {
		return m.VideoId
	}
	return 0
}

func (m *DouyinFavoriteActionRequest) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type DouyinFavoriteActionResponse struct {
	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	StatusMsg  string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
}

func (m *DouyinFavoriteActionResponse) Reset()         { *m = DouyinFavoriteActionResponse{} }
func (m *DouyinFavoriteActionResponse) String() string { return proto.CompactTextString(m) }
func (*DouyinFavoriteActionResponse) ProtoMessage()    {}
func (*DouyinFavoriteActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d331d96d24e0e82b, []int{1}
}
func (m *DouyinFavoriteActionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DouyinFavoriteActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DouyinFavoriteActionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DouyinFavoriteActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DouyinFavoriteActionResponse.Merge(m, src)
}
func (m *DouyinFavoriteActionResponse) XXX_Size() int {
	return m.Size()
}
func (m *DouyinFavoriteActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DouyinFavoriteActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DouyinFavoriteActionResponse proto.InternalMessageInfo

func (m *DouyinFavoriteActionResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *DouyinFavoriteActionResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

type DouyinFavoriteListRequest struct {
	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *DouyinFavoriteListRequest) Reset()         { *m = DouyinFavoriteListRequest{} }
func (m *DouyinFavoriteListRequest) String() string { return proto.CompactTextString(m) }
func (*DouyinFavoriteListRequest) ProtoMessage()    {}
func (*DouyinFavoriteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d331d96d24e0e82b, []int{2}
}
func (m *DouyinFavoriteListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DouyinFavoriteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DouyinFavoriteListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DouyinFavoriteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DouyinFavoriteListRequest.Merge(m, src)
}
func (m *DouyinFavoriteListRequest) XXX_Size() int {
	return m.Size()
}
func (m *DouyinFavoriteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DouyinFavoriteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DouyinFavoriteListRequest proto.InternalMessageInfo

func (m *DouyinFavoriteListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DouyinFavoriteListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DouyinFavoriteListResponse struct {
	StatusCode int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	StatusMsg  string   `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	VideoList  []*Video `protobuf:"bytes,3,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
}

func (m *DouyinFavoriteListResponse) Reset()         { *m = DouyinFavoriteListResponse{} }
func (m *DouyinFavoriteListResponse) String() string { return proto.CompactTextString(m) }
func (*DouyinFavoriteListResponse) ProtoMessage()    {}
func (*DouyinFavoriteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d331d96d24e0e82b, []int{3}
}
func (m *DouyinFavoriteListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DouyinFavoriteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DouyinFavoriteListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DouyinFavoriteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DouyinFavoriteListResponse.Merge(m, src)
}
func (m *DouyinFavoriteListResponse) XXX_Size() int {
	return m.Size()
}
func (m *DouyinFavoriteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DouyinFavoriteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DouyinFavoriteListResponse proto.InternalMessageInfo

func (m *DouyinFavoriteListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *DouyinFavoriteListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *DouyinFavoriteListResponse) GetVideoList() []*Video {
	if m != nil {
		return m.VideoList
	}
	return nil
}

func init() {
	proto.RegisterType((*DouyinFavoriteActionRequest)(nil), "douyin.extra.first.douyin_favorite_action_request")
	proto.RegisterType((*DouyinFavoriteActionResponse)(nil), "douyin.extra.first.douyin_favorite_action_response")
	proto.RegisterType((*DouyinFavoriteListRequest)(nil), "douyin.extra.first.douyin_favorite_list_request")
	proto.RegisterType((*DouyinFavoriteListResponse)(nil), "douyin.extra.first.douyin_favorite_list_response")
}

func init() { proto.RegisterFile("favorite.proto", fileDescriptor_d331d96d24e0e82b) }

var fileDescriptor_d331d96d24e0e82b = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0xac, 0x09, 0x6d, 0xe9, 0xab, 0xd4, 0xc1, 0x42, 0x22, 0x20, 0xea, 0x46, 0x99, 0x32, 0x19,
	0x01, 0x23, 0x1b, 0x4c, 0x95, 0xe8, 0x12, 0x21, 0x06, 0x96, 0x28, 0xd4, 0xaf, 0x91, 0x55, 0x1a,
	0x07, 0xdb, 0xa9, 0xe8, 0x37, 0xb0, 0x20, 0xbe, 0x8a, 0xb1, 0x23, 0x23, 0x6a, 0x7f, 0x04, 0x25,
	0x0e, 0x0b, 0x52, 0x17, 0xc4, 0x78, 0xf7, 0xee, 0xce, 0x67, 0xfb, 0xc1, 0x60, 0x96, 0x2e, 0x95,
	0x96, 0x16, 0x79, 0xa1, 0x95, 0x55, 0x94, 0x0a, 0x55, 0xae, 0x64, 0xce, 0xf1, 0xc5, 0xea, 0x94,
	0xcf, 0xa4, 0x36, 0xf6, 0x04, 0x4a, 0x83, 0xda, 0xcd, 0xc3, 0x57, 0x02, 0xcc, 0x49, 0x92, 0x1f,
	0x67, 0x92, 0x4e, 0xad, 0x54, 0x79, 0xa2, 0xf1, 0xb9, 0x44, 0x63, 0xe9, 0x11, 0x74, 0x2b, 0x43,
	0x22, 0x85, 0x4f, 0x02, 0x12, 0x79, 0x71, 0xa7, 0x82, 0x63, 0x41, 0x0f, 0xa1, 0x6d, 0xd5, 0x1c,
	0x73, 0x7f, 0x2f, 0x20, 0x51, 0x2f, 0x76, 0x80, 0x1e, 0xc3, 0xc1, 0x52, 0x0a, 0x54, 0x95, 0xde,
	0xab, 0xf5, 0xdd, 0x1a, 0x8f, 0x05, 0x1d, 0x41, 0xbf, 0xc9, 0xb6, 0xab, 0x02, 0xfd, 0xfd, 0x80,
	0x44, 0xed, 0x18, 0x1c, 0x75, 0xb7, 0x2a, 0x30, 0x4c, 0x61, 0xb4, 0xb3, 0x8c, 0x29, 0x54, 0x6e,
	0xb0, 0xca, 0x30, 0x36, 0xb5, 0xa5, 0x49, 0xa6, 0x4a, 0x60, 0xdd, 0xa8, 0x1d, 0x83, 0xa3, 0x6e,
	0x94, 0x40, 0x3a, 0x84, 0x06, 0x25, 0x0b, 0x93, 0x35, 0xd5, 0x7a, 0x8e, 0x99, 0x98, 0x2c, 0x9c,
	0xc0, 0xe9, 0xef, 0x23, 0x9e, 0xa4, 0xb1, 0x7f, 0xbc, 0x6d, 0xf8, 0x4e, 0x60, 0xb8, 0x23, 0xef,
	0x7f, 0x0a, 0xd3, 0x73, 0x00, 0xf7, 0x9e, 0x55, 0xac, 0xef, 0x05, 0x5e, 0xd4, 0xbf, 0xa0, 0xbc,
	0xf9, 0xd6, 0xa9, 0xd2, 0xc8, 0xef, 0xab, 0x71, 0xdc, 0xab, 0x55, 0xb7, 0xd2, 0xd8, 0xeb, 0xe8,
	0x63, 0xc3, 0xc8, 0x7a, 0xc3, 0xc8, 0xd7, 0x86, 0x91, 0xb7, 0x2d, 0x6b, 0xad, 0xb7, 0xac, 0xf5,
	0xb9, 0x65, 0xad, 0x87, 0x01, 0xe7, 0x67, 0xc5, 0x3c, 0xbb, 0x5a, 0xa0, 0x31, 0x69, 0x86, 0x8f,
	0x9d, 0x7a, 0x0b, 0x2e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x4a, 0xc6, 0xcf, 0x37, 0x02,
	0x00, 0x00,
}

func (m *DouyinFavoriteActionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DouyinFavoriteActionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DouyinFavoriteActionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActionType != 0 {
		i = encodeVarintFavorite(dAtA, i, uint64(m.ActionType))
		i--
		dAtA[i] = 0x20
	}
	if m.VideoId != 0 {
		i = encodeVarintFavorite(dAtA, i, uint64(m.VideoId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintFavorite(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x12
	}
	if m.UserId != 0 {
		i = encodeVarintFavorite(dAtA, i, uint64(m.UserId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DouyinFavoriteActionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DouyinFavoriteActionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DouyinFavoriteActionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StatusMsg) > 0 {
		i -= len(m.StatusMsg)
		copy(dAtA[i:], m.StatusMsg)
		i = encodeVarintFavorite(dAtA, i, uint64(len(m.StatusMsg)))
		i--
		dAtA[i] = 0x12
	}
	if m.StatusCode != 0 {
		i = encodeVarintFavorite(dAtA, i, uint64(m.StatusCode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DouyinFavoriteListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DouyinFavoriteListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DouyinFavoriteListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintFavorite(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x12
	}
	if m.UserId != 0 {
		i = encodeVarintFavorite(dAtA, i, uint64(m.UserId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DouyinFavoriteListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DouyinFavoriteListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DouyinFavoriteListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VideoList) > 0 {
		for iNdEx := len(m.VideoList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VideoList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFavorite(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.StatusMsg) > 0 {
		i -= len(m.StatusMsg)
		copy(dAtA[i:], m.StatusMsg)
		i = encodeVarintFavorite(dAtA, i, uint64(len(m.StatusMsg)))
		i--
		dAtA[i] = 0x12
	}
	if m.StatusCode != 0 {
		i = encodeVarintFavorite(dAtA, i, uint64(m.StatusCode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFavorite(dAtA []byte, offset int, v uint64) int {
	offset -= sovFavorite(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DouyinFavoriteActionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserId != 0 {
		n += 1 + sovFavorite(uint64(m.UserId))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovFavorite(uint64(l))
	}
	if m.VideoId != 0 {
		n += 1 + sovFavorite(uint64(m.VideoId))
	}
	if m.ActionType != 0 {
		n += 1 + sovFavorite(uint64(m.ActionType))
	}
	return n
}

func (m *DouyinFavoriteActionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StatusCode != 0 {
		n += 1 + sovFavorite(uint64(m.StatusCode))
	}
	l = len(m.StatusMsg)
	if l > 0 {
		n += 1 + l + sovFavorite(uint64(l))
	}
	return n
}

func (m *DouyinFavoriteListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserId != 0 {
		n += 1 + sovFavorite(uint64(m.UserId))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovFavorite(uint64(l))
	}
	return n
}

func (m *DouyinFavoriteListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StatusCode != 0 {
		n += 1 + sovFavorite(uint64(m.StatusCode))
	}
	l = len(m.StatusMsg)
	if l > 0 {
		n += 1 + l + sovFavorite(uint64(l))
	}
	if len(m.VideoList) > 0 {
		for _, e := range m.VideoList {
			l = e.Size()
			n += 1 + l + sovFavorite(uint64(l))
		}
	}
	return n
}

func sovFavorite(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFavorite(x uint64) (n int) {
	return sovFavorite(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DouyinFavoriteActionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFavorite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: douyin_favorite_action_request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: douyin_favorite_action_request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFavorite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFavorite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoId", wireType)
			}
			m.VideoId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VideoId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionType", wireType)
			}
			m.ActionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFavorite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFavorite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DouyinFavoriteActionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFavorite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: douyin_favorite_action_response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: douyin_favorite_action_response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			m.StatusCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFavorite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFavorite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFavorite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFavorite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DouyinFavoriteListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFavorite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: douyin_favorite_list_request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: douyin_favorite_list_request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFavorite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFavorite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFavorite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFavorite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DouyinFavoriteListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFavorite
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: douyin_favorite_list_response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: douyin_favorite_list_response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			m.StatusCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFavorite
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFavorite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFavorite
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFavorite
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VideoList = append(m.VideoList, &Video{})
			if err := m.VideoList[len(m.VideoList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFavorite(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFavorite
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFavorite(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFavorite
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFavorite
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFavorite
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFavorite
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFavorite
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFavorite        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFavorite          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFavorite = fmt.Errorf("proto: unexpected end of group")
)
